import { useEffect, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { KeyRound, Loader2, Mail } from 'lucide-react';
import API from '../api';

export default function TeamAccess({ onLogin }: { onLogin: () => void }) {
  const [params] = useSearchParams(); const navigate = useNavigate(); const token = params.get('token') || '';
  const [otp, setOtp] = useState(''); const [email, setEmail] = useState(''); const [sent, setSent] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const sendOtp = async () => { if (!token) { setError('This team link is invalid.'); return; } setLoading(true); setError(''); try { const response = await API.post(`/team/access/${token}/request-otp`); setEmail(response.data.email); setSent(true); } catch (err: any) { setError(err.response?.data?.message || 'Could not send OTP.'); } finally { setLoading(false); } };
  useEffect(() => { void sendOtp(); }, []);
  const verify = async (event: React.FormEvent) => { event.preventDefault(); setLoading(true); setError(''); try { const response = await API.post(`/team/access/${token}/verify-otp`, { otp }); localStorage.setItem('token', response.data.token); localStorage.setItem('user', JSON.stringify(response.data.user)); onLogin(); navigate('/'); } catch (err: any) { setError(err.response?.data?.message || 'Invalid or expired OTP.'); } finally { setLoading(false); } };
  return <div className="min-h-[85vh] flex items-center justify-center px-4"><div className="w-full max-w-md rounded-2xl border border-slate-200 bg-white p-8 shadow-sm"><div className="text-center"><div className="inline-flex rounded-2xl border border-emerald-100 bg-emerald-50 p-3 text-emerald-600"><KeyRound size={28} /></div><h1 className="mt-4 text-2xl font-extrabold text-slate-900">Team workspace access</h1><p className="mt-2 text-xs text-slate-500">Verify the OTP sent to your invited email. No separate signup is needed.</p></div>{error && <p className="mt-5 rounded-lg border border-rose-200 bg-rose-50 p-3 text-xs font-semibold text-rose-700">{error}</p>}{!sent ? <div className="mt-6 text-center text-sm text-slate-500"><Loader2 className="mx-auto animate-spin text-emerald-600" /> <p className="mt-3">Sending your secure OTP...</p></div> : <form onSubmit={verify} className="mt-6 space-y-4"><p className="flex items-center justify-center gap-1.5 text-xs font-semibold text-slate-600"><Mail size={14} /> {email}</p><input required maxLength={6} value={otp} onChange={(event) => setOtp(event.target.value)} placeholder="000000" className="w-full rounded-xl border border-slate-300 py-3 text-center font-mono text-2xl tracking-[0.45em] text-emerald-700 outline-none focus:border-emerald-600" /><button disabled={loading} className="w-full rounded-xl bg-emerald-600 py-3 text-sm font-bold text-white hover:bg-emerald-700 disabled:bg-slate-300">{loading ? 'Verifying...' : 'Verify & Open Workspace'}</button><button type="button" disabled={loading} onClick={sendOtp} className="w-full text-xs font-bold text-slate-500 hover:text-emerald-700">Resend OTP</button></form>}</div></div>;
}
